name: Build

on:
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'cmd/**'
      - 'pkg/**'
      - 'test/**'
      - 'go.mod'
      - 'go.sum'
      - 'makefile'
      - '!**/*.md'
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Declare default permissions as read only.
permissions: read-all

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        
      - name: Prepend the patch path to the PATH variable
        run: |
          echo "Prepend the patched cmsis-toolbox version path to the PATH variable"
          export PATH="/patch/cmsis-toolbox-linux-amd64${PATH:+:${PATH}}"
          echo $PATH

