name: Build

on:
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'cmd/**'
      - 'pkg/**'
      - 'test/**'
      - 'go.mod'
      - 'go.sum'
      - 'makefile'
      - '!**/*.md'
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Declare default permissions as read only.
permissions: read-all

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Prepend the patch path to the PATH variable
        if: ${{ steps.check_dir.outputs.exists == '1' }}
        run: |
          echo "Prepend the patched cmsis-toolbox version path to the PATH variable"
          export PATH="/patch/cmsis-toolbox-linux-amd64${PATH:+:${PATH}}"
          echo $PATH

